//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTaiSan_UserManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential
    {
        public string UserGroupID { get; set; }
        public string RoleID { get; set; }
        public int ID { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
