//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTaiSan_UserManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestructivelDevice
    {
        public int Id { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public Nullable<System.DateTime> DateOfDestructive { get; set; }
        public Nullable<int> TypeOfDestructive { get; set; }
        public string AddressOfDestructive { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual DestructiveType DestructiveType { get; set; }
        public virtual Device Device { get; set; }
        public virtual User User { get; set; }
    }
}
