//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTaiSan_UserManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDevice
    {
        public int Id { get; set; }
        public Nullable<int> UserRequest { get; set; }
        public Nullable<System.DateTime> DateOfRequest { get; set; }
        public Nullable<System.DateTime> DateOfUse { get; set; }
        public string DeviceName { get; set; }
        public Nullable<int> TypeOfDevice { get; set; }
        public string Configuration { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> UserApproved { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> NumDevice { get; set; }
        public string NoteProcess { get; set; }
        public string NoteReasonRefuse { get; set; }
        public string NameUserApproved { get; set; }
    
        public virtual DeviceType DeviceType { get; set; }
        public virtual User User { get; set; }
    }
}
